### ISSUE TITLE
DisqusJS is {} when I import it

### ISSUE THREAD

**Issue by luyilin** [SukkaW/DisqusJS#13]
I am confused how to use it. Is there anything wrong when I import it?
Here is the code, hope for your help~
https://github.com/luyilin/minemine/blob/32ce31f64b007ee7100eb749ff6e12f5c734c14d/themes/layouts/comment.vue#L39

**Comment by SukkaW** [comment]
README give the NPM usage of DisqusJS should work with module bundler.
And `new DisqusJS` should be called when you need to start a new DIsqusJS instance.

**Comment by luyilin** [comment]
It seemed miss a `export default DisqusJS` in src/index.js, so cannot import DisqusJS successfully 😳 What do you think about it?
