### ISSUE TITLE
当使用pjax时，disqusjs显示异常

### ISSUE THREAD

**Issue by tetsaicn** [SukkaW/DisqusJS#14]
直接打开[文章](https://blog.tetsai.com/archives/iam-come-back-again.html)
很明显，disqus正常工作了
但是如果从[首页](https://blog.tetsai.com/)中打开这篇文章，会造成这样的效果
![image](https://user-images.githubusercontent.com/24486768/48671508-752de880-eb64-11e8-8f43-e1d7f7fa07d1.png)
APlayer有类似的问题，但可以通过pjax刷新时回调
`if (typeof aplayers !== 'undefined'){
    for (var i = 0; i < aplayers.length; i++) {
        try {aplayers[i].destroy()} catch(e){}
    }
}
loadMeting();`
解决，不知道disqusjs该如何正常回调，或是增加原生pjax支持？

**Comment by tetsaicn** [comment]
已找到相关PR： #4 
README藏得太深，没看见
closed

**Comment by SukkaW** [comment]
@tetsaicn 目前 DisqusJS 一律使用 `new DisqusJS` 方法创建一个 DisqusJS 实例，跳转新页面时直接重新创建一个新的 DisqusJS 实例即可。

**Comment by zhangzq** [comment]
> @tetsaicn 目前 DisqusJS 一律使用 `new DisqusJS` 方法创建一个 DisqusJS 实例，跳转新页面时直接重新创建一个新的 DisqusJS 实例即可。

遇到同样的问题了。重新创建一个新的也不行。就像上面截图里显示的那样，评论显示都正常，就是那个“加载中..."的一大串提示不会自动消失。
