### ISSUE TITLE
exports is not defined

### ISSUE THREAD

**Issue by imlonghao** [SukkaW/DisqusJS#17]
在 #15 之后的版本浏览器控制台会报错：

```
Uncaught ReferenceError: exports is not defined
    at disqus.js:6
```

https://suka.js.org/DisqusJS/ Firefox / Chrome 能复现这个问题

**Comment by SukkaW** [comment]
#13 
I think now I have to make maintain 2 versions, one for module bundler and one for browser,

**Comment by SukkaW** [comment]
From 1.1.0, DisqusJS will functionally support AMD & CMD.
