### ISSUE TITLE
无代理状态，首次访问（或清掉 disqusjs_mode）不会加载评论

### ISSUE THREAD

**Issue by DIYgod** [SukkaW/DisqusJS#2]
预期加载基础模式，实际什么都没有加载出来

demo 稳定复现

**Comment by SukkaW** [comment]
应该是 PJAX 的问题，我回头暴露一个函数出来吧。

**Comment by SukkaW** [comment]
奇怪。。在我这里，不挂代理、清除 localStorage 后 demo 都是正常的。。。有没有 console 输出的内容?

**Comment by SukkaW** [comment]
DIYgod 有没有试过自用建的 DISQUS API 反代测试一下？

**Comment by DIYgod** [comment]
具体表现是这样的

![](https://i.loli.net/2018/10/15/5bc450b8d1302.jpg)

console 没什么异常

![](https://i.loli.net/2018/10/15/5bc450ba9002e.jpg)

只有第一次会不显示，刷新一下就好了

我这里稳定复现...用无痕模式打开试试？

**Comment by SukkaW** [comment]
`ERR_TUNNEL_CONNECTION_FAILED` 应该是 DIY 的代理出现了问题吧。。
我这里使用 Dev Tools 的 Request Blocking 阻止 `disqus.com/favicon.ico` 的请求时仍然会切换到「评论基础模式」。。。
我试试 `ERR_TUNNEL_CONNECTION_FAILED` 能不能触发 onerror 事件

**Comment by DIYgod** [comment]
不是，ERR_TUNNEL_CONNECTION_FAILED 是 disqus.com/favicon.ico 的请求

我这里只要删掉 disqusjs_mode 第一次访问就会空白...迷

**Comment by SukkaW** [comment]
奇怪。。DIYgod 试试在无痕模式下、先打开 Dev Tools 里的 Request Blocking、Block 掉 `https://disqus.com/favicon.ico` URL，然后再打开 https://suka.js.org/DisqusJS 试试？

**Comment by DIYgod** [comment]
Block 掉是好的，惊了

**Comment by SukkaW** [comment]
`ERR_TUNNEL_CONNECTION_FAILED` 我无法模拟。。但是在 `ERR_PROXY_CONNECTION_FAILED` 情况下应该会正常触发 onerror 事件。

DisqusJS 检测访客的 Disqus 可用性是通过检测 disqus.com/favicon.ico 和 ${disqusjs.config.shortname}.disqus.com/favicon.ico 是否能正常加载，如果有一个加载出错或超时（2s）就判定 Disqus 不可用。

**Comment by SukkaW** [comment]
即使 `ERR_TUNNEL_CONNECTION_FAILED` 不能触发 onerror 事件，DisqusJS 做了 2s 超时的 fallback 的，应该仍然会切换到「评论基础模式」的。。

**Comment by SukkaW** [comment]
@DIYgod DIYgod 检查一下，不 Block 掉 URL，然后当出现一片空白的时候，localStorage 里 `disqusjs_mode` 的值是不是 `disqus`？

**Comment by DIYgod** [comment]
是 dsqjs

我用的 surge，出问题的是设置 surge 不走代理，但是我把 surge 都关掉就是可以正常显示的

**Comment by SukkaW** [comment]
呜，那么窝知道问题出在哪里惹。。DisqusJS 对超时的处理 Bug。。。
