### ISSUE TITLE
InstantClick下异常

### ISSUE THREAD

**Issue by zhangzq** [SukkaW/DisqusJS#21]
问题和 https://github.com/SukkaW/DisqusJS/issues/14 这里的截图完全一样。

当页面内通过InstantClick刷新时，评论会正常显示。但那个“加载中..."的一大串提示不会自动消失。按F5刷新都是正常的。

**Comment by zhangzq** [comment]
加了一个 `window.DISQUS = null;`解决了。

**Comment by SukkaW** [comment]
有没有 Demo 和示例代码？

DisqusJS 在发布 1.2.0 时 README 添加了 PJAX 相关的提示：

> 如果你在使用 DisqusJS v0.2.5 版本，需要在 PJAX 的页面跳转事件下销毁 Disqus 实例（Disqus 不支持 PJAX）、并通过 `window.disqusjs.load();` 重新加载 DisqusJS。DisqusJS v0.2.5 版本支持自动判断当前页面是否存在 `#disqus_thread` 容器，如果容器不存在就不加载。  
> DisqusJS v1.0.0 及之后的版本使用了新的方法加载 DisqusJS，并去除了对 `#disqus_thread` 容器的判断，在没有容器的页面初始化 DisqusJS 实例会报错。在切换页面时需要销毁已有的 Disqus 实例和 DisqusJS 实例，然后重新初始化一个新的 DisqusJS 实例。
