### ISSUE TITLE
CROS 问题

### ISSUE THREAD

**Issue by wafer-li** [SukkaW/DisqusJS#28]
![image](https://user-images.githubusercontent.com/12459199/58371923-d0dc9280-7f48-11e9-959e-846ae3ad03ea.png)

![image](https://user-images.githubusercontent.com/12459199/58371944-f36eab80-7f48-11e9-9d97-fa8b2b95f657.png)

![image](https://user-images.githubusercontent.com/12459199/58371971-52342500-7f49-11e9-8aa8-7a696af5dd41.png)

![image](https://user-images.githubusercontent.com/12459199/58371978-60824100-7f49-11e9-90cc-95bb72605d02.png)

请问大佬有没有什么解决办法？

**Comment by SukkaW** [comment]
请以 2 字/分钟 的语速、逐字大声朗读 README 中关于 Disqus API Application 设置部分。

**Comment by wafer-li** [comment]
不好意思，是我星际了 :joy:

**Comment by saltbo** [comment]
打扰一下 是我沙雕了么 为啥我在 Disqus API Application 设置部分 没有找到解决办法。

我理解这个应该是反代没有开跨域导致的吧？用的是默认提供的反代

**Comment by SukkaW** [comment]
@saltbo 

> 请以 2 字/分钟 的语速、逐字大声朗读 README 中关于 Disqus API Application 设置部分。

**Comment by saltbo** [comment]
认真看过了，已经设置了域名，但是昨天晚上一直不行。不知道是有生效时间还是Disqus昨天晚上出问题了。因为昨天我去你的网站试了下 有时候也会报没有Origin
