### ISSUE TITLE
评论基础模式是哪个神仙做出来的～。～

### ISSUE THREAD

**Issue by zzz6519003** [SukkaW/DisqusJS#34]

**Comment by SukkaW** [comment]
是我。

**Comment by zzz6519003** [comment]
好奇原理！

**Comment by SukkaW** [comment]
Disqus 的 API（可能要用到 Disqus 的私有 API），反代 API、然后把数据渲染成评论条目就行了。

Disqus API 的 create 方法需要空 Referrer 和 空 Origin，所以纯前端实现评论回复和新增 Forum 是不行的。不过我觉得，纯前端看看评论效果也不差了，尤其是对于静态博客来说。
