### ISSUE TITLE
Thread初始化失败

### ISSUE THREAD

**Issue by Easteriv** [SukkaW/DisqusJS#38]
![2019-10-19_205937](https://user-images.githubusercontent.com/40998471/67145566-237e6880-f2b5-11e9-859d-fab8c6fbfd3e.png)
你好，当时按照文档描述的diygod大佬升级disqus方法进行操作，发现会出现这种情况，请问这是怎么回事呢？有的过一段时间又可以了。

**Comment by SukkaW** [comment]
Since DisqusJS is only a pure front-end project which doesn't require any server, so create thread at Disqus requires user manually switches to Disqus Mode.

**Comment by Easteriv** [comment]
oh,谢谢大佬的及时回复，我明白啦

**Comment by RebornQ** [comment]
@SukkaW  我也遇到了这个问题～

确定已经存在评论，而且通过抓包看了获取 `list.json ` 后的response.posts是为1的；

通过对比发现显示 `Thread不存在` 的页面在获取了 `list.json` 后少了一个  `https://disqus.skk.moe/disqus/3.0/threads/listPostsThreaded?xxx...`   的 `GET`  请求。

百思不得其解，望 Sukka 帮忙解决一下

**Comment by SukkaW** [comment]
> Since DisqusJS is only a pure front-end project which doesn't require any server, so create thread at Disqus requires user manually switches to Disqus Mode.

@RebornQ Are you blinded?
