### ISSUE TITLE
dark mode support

### ISSUE THREAD

**Issue by chenzhiwei** [SukkaW/DisqusJS#40]
Do you have plan to support dark mode?

```
@media (prefers-color-scheme: dark) {
}
```

**Comment by SukkaW** [comment]
You could add `dark-mode` support to your website by yourself. All DisqusJS elements are wrapped inside `div#dsqjs` and all class names are `dsqjs-` prefixed.

**Comment by chenzhiwei** [comment]
yes, i did this for now.

it will be great if this can be implemented in upstrem.

**Comment by eallion** [comment]
That's sound awesome

**Comment by ljcbaby** [comment]
![](https://cdn.jsdelivr.net/gh/ljcbaby/image@master/20201003203237.png)
To be honest, is there no dark mode in DisqusJS itself, or is there something wrong with my site configuration?
In the picture, I can only see the text when I select them.

By the way, is it normal that there is "1 comment" showed on the top, but it says empty in follows?

(English is not my native language; please excuse typing errors.)
