### ISSUE TITLE
我想请教一下使用 Cloudflare Workers 进行反向代理时的跨域问题

### ISSUE THREAD

**Issue by aiokr** [SukkaW/DisqusJS#41]
在 Cloudflare Workers 配置反向代理后博客这样报错：
![image](https://user-images.githubusercontent.com/25877104/72091545-5e8bb780-334b-11ea-8419-056e5c5c1586.png)
向问一下怎样填写 Cloudflare Workers 的代码才能正确地配置跨域。

**Comment by SukkaW** [comment]
之所以没法跨域是因为你的请求返回的是 404 状态码，404 是没有 CORS 一说的。先去检查一下 Cloudflare Workers 上的 Route 是不是配错了。

**Comment by aiokr** [comment]
噢我找到问题了，应该在api那里填写代理到 disqus.com/api/ 的地址
谢谢大佬~
