### ISSUE TITLE
a typo of README

### ISSUE THREAD

**Issue by eallion** [SukkaW/DisqusJS#44]
`<script src="https://cdn.jsdelivr.net/npm/disqusjs@1.3dist/disqus.js"></script>`
 =>
`<script src="https://cdn.jsdelivr.net/npm/disqusjs@1.3/dist/disqus.js"></script>`

**Comment by SukkaW** [comment]
Would you mind opening a PR to fix IT?

**Comment by eallion** [comment]
#45
