### ISSUE TITLE
自定义 url 无效的问题

### ISSUE THREAD

**Issue by inkss** [SukkaW/DisqusJS#53]
![image](https://user-images.githubusercontent.com/31947043/89506521-d34da400-d7fd-11ea-9d55-10fc40ee5e98.png)

比如说这样子设置的，但是不知道为什么disqus_config像是没生效一样，实在不知道为啥啊，disqus的文档里也是这样写的，可是就是没生效。

发生在本地测试的时候

**Comment by SukkaW** [comment]
[RTFM](https://github.com/SukkaW/DisqusJS#%E8%B0%83%E8%AF%95%E8%BF%9B%E9%98%B6%E4%BD%BF%E7%94%A8--%E5%BC%80%E5%8F%91%E7%9B%B8%E5%85%B3)

**Comment by inkss** [comment]
很神奇，按照上面所说绑定到 window 上了，所以把 var 定义的直接改为 window.disqus_config 生效了
